### PR TITLE
Fix/object queries

### LINKED ISSUE #354: object queries fail
Different values for ?o either return incorrect results or throws errors.

```
(def conn (test-utils/create-conn))
(def ledger @(fluree/create conn "query/everything" {:context {:ex "http://example.org/ns/"}}))
(def db @(fluree/stage
           (fluree/db ledger)
           {:graph [{:id          :ex/bob,
                     :type        :ex/User,
                     :schema/name "Bob"
                     :schema/age  22}]}))

;; returns wrong result
@(fluree/query db {:select ['?s '?p]
                   :where [['?s '?p 22]]})
;; => []

;; throws error
@(fluree/query db {:select ['?s '?p]
                   :where [['?s '?p "Bob"]]})
```

The error thrown on the second query:
```
ERROR f.db.query.exec.where - Error resolving flake range
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at fluree.db.flake$cmp_long.invokeStatic(flake.cljc:310)
	at fluree.db.flake$cmp_long.invoke(flake.cljc:309)
	at fluree.db.flake$cmp_subj.invokeStatic(flake.cljc:318)
	at fluree.db.flake$cmp_subj.invoke(flake.cljc:314)
	at fluree.db.flake$cmp_flakes_opst.invokeStatic(flake.cljc:402)
	at fluree.db.flake$cmp_flakes_opst.invoke(flake.cljc:400)
	at clojure.lang.AFunction.compare(AFunction.java:51)
	at clojure.data.avl$insert_BANG_.invokeStatic(avl.clj:797)
	at clojure.data.avl$insert_BANG_.invoke(avl.clj:791)
	at clojure.data.avl.AVLTransientMap.assoc(avl.clj:1606)
	at clojure.data.avl.AVLTransientSet.conj(avl.clj:1810)
	at clojure.core$conj_BANG_.invokeStatic(core.clj:3367)
	at clojure.core$conj_BANG_.invoke(core.clj:3359)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:119)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at clojure.data.avl$sorted_set_by.invokeStatic(avl.clj:1933)
	at clojure.data.avl$sorted_set_by.doInvoke(avl.clj:1928)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at fluree.db.flake$sorted_set_by.invokeStatic(flake.cljc:526)
	at fluree.db.flake$sorted_set_by.doInvoke(flake.cljc:524)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at fluree.db.query.range$resolve_flake_slices.invokeStatic(range.cljc:154)
	at fluree.db.query.range$resolve_flake_slices.invoke(range.cljc:146)
	at fluree.db.query.exec.where$resolve_flake_range$fn__29663$state_machine__7578__auto____29708$fn__29710.invoke(where.cljc:51)
	at fluree.db.query.exec.where$resolve_flake_range$fn__29663$state_machine__7578__auto____29708.invoke(where.cljc:32)
	at clojure.core.async.impl.runtime$run_state_machine.invokeStatic(runtime.clj:62)
	at clojure.core.async.impl.runtime$run_state_machine.invoke(runtime.clj:61)
	at clojure.core.async.impl.runtime$run_state_machine_wrapped.invokeStatic(runtime.clj:66)
	at clojure.core.async.impl.runtime$run_state_machine_wrapped.invoke(runtime.clj:64)
	at fluree.db.query.exec.where$resolve_flake_range$fn__29663.invoke(where.cljc:32)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__1977$fn__1978.invoke(concurrent.clj:29)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:829)
ERROR fluree.db.json-ld.api - #error {
 :cause "class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')"
 :via
 [{:type java.lang.ClassCastException
   :message "class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')"
   :at [fluree.db.flake$cmp_long invokeStatic "flake.cljc" 310]}]
 :trace
 [[fluree.db.flake$cmp_long invokeStatic "flake.cljc" 310]
  [fluree.db.flake$cmp_long invoke "flake.cljc" 309]
  [fluree.db.flake$cmp_subj invokeStatic "flake.cljc" 318]
  [fluree.db.flake$cmp_subj invoke "flake.cljc" 314]
  [fluree.db.flake$cmp_flakes_opst invokeStatic "flake.cljc" 402]
  [fluree.db.flake$cmp_flakes_opst invoke "flake.cljc" 400]
  [clojure.lang.AFunction compare "AFunction.java" 51]
  [clojure.data.avl$insert_BANG_ invokeStatic "avl.clj" 797]
  [clojure.data.avl$insert_BANG_ invoke "avl.clj" 791]
  [clojure.data.avl.AVLTransientMap assoc "avl.clj" 1606]
  [clojure.data.avl.AVLTransientSet conj "avl.clj" 1810]
  [clojure.core$conj_BANG_ invokeStatic "core.clj" 3367]
  [clojure.core$conj_BANG_ invoke "core.clj" 3359]
  [clojure.lang.ArraySeq reduce "ArraySeq.java" 119]
  [clojure.core$reduce invokeStatic "core.clj" 6885]
  [clojure.core$reduce invoke "core.clj" 6868]
  [clojure.data.avl$sorted_set_by invokeStatic "avl.clj" 1933]
  [clojure.data.avl$sorted_set_by doInvoke "avl.clj" 1928]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invokeStatic "core.clj" 669]
  [clojure.core$apply invoke "core.clj" 662]
  [fluree.db.flake$sorted_set_by invokeStatic "flake.cljc" 526]
  [fluree.db.flake$sorted_set_by doInvoke "flake.cljc" 524]
  [clojure.lang.RestFn invoke "RestFn.java" 439]
  [fluree.db.query.range$resolve_flake_slices invokeStatic "range.cljc" 154]
  [fluree.db.query.range$resolve_flake_slices invoke "range.cljc" 146]
  [fluree.db.query.exec.where$resolve_flake_range$fn__29663$state_machine__7578__auto____29708$fn__29710 invoke "where.cljc" 51]
  [fluree.db.query.exec.where$resolve_flake_range$fn__29663$state_machine__7578__auto____29708 invoke "where.cljc" 32]
  [clojure.core.async.impl.runtime$run_state_machine invokeStatic "runtime.clj" 62]
  [clojure.core.async.impl.runtime$run_state_machine invoke "runtime.clj" 61]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invokeStatic "runtime.clj" 66]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invoke "runtime.clj" 64]
  [fluree.db.query.exec.where$resolve_flake_range$fn__29663 invoke "where.cljc" 32]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 628]
  [clojure.core.async.impl.concurrent$counted_thread_factory$reify__1977$fn__1978 invoke "concurrent.clj" 29]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 829]]}
```

### PR DESCRIPTION
**Pull request by zonotope**
This patch returns an error message instead of incorrect and confusing results when a query scans the OPST index looking for an non-subject id integer value, and a more descriptive error message when scanning for a non-integer object value in the OPST index by checking the data type of object values and only accepting iris. 

I also snuck in some optimizations of select-distinct query processing that uses one less async channel by applying a transducer directly to the output channel of the select step. 

Fixes #354

### CODE REVIEW

File: test/fluree/db/query/misc_queries_test.clj [hunk 1]
```diff
@@ -32,26 +32,26 @@
                                 :where  [['?s :type :ex/User]]}))))))
 
 (deftest ^:integration s+p+o-full-db-queries
```
Comment (mpoffald) [inline test/fluree/db/query/misc_queries_test.clj:34]: The name `s+p+o-full-db-queries` doesn't make sense for this test anymore. We might want to rename it or create a different `deftest` for these opst tests

File: test/fluree/db/query/misc_queries_test.clj [hunk 2]
```diff
@@ -237,5 +237,13 @@
                   ["fluree:commit:sha256:bbstbkfuob2d73ubsc3xvqckbmn7z35esq5k7i3rolj7hed7li2ox"
                    :f/context
                    "fluree:memory://b6dcf8968183239ecc7a664025f247de5b7859ac18cdeaace89aafc421eeddee"]]
-                @(fluree/query db* {:select ['?s '?p '?o]
-                                    :where  [['?s '?p '?o]]}))))))))
+                 @(fluree/query db* {:select ['?s '?p '?o]
+                                     :where  [['?s '?p '?o]]})))))
+      (testing "Illegal reference queries"
+        (let [test-subject @(fluree/query db {:select ['?s '?p]
+                                              :where [['?s '?p 22]]})]
```
Comment (mpoffald) [inline test/fluree/db/query/misc_queries_test.clj:244]: For completion's sake, could we also have a test for the non-iri string object case that was in the bug report?

**Review by mpoffald — APPROVED** [review]
I had a couple of small nitpicks on the test file, but the fix itself looks good to me!

File: test/fluree/db/query/misc_queries_test.clj [hunk 3]
```diff
@@ -237,5 +237,13 @@
                   ["fluree:commit:sha256:bbstbkfuob2d73ubsc3xvqckbmn7z35esq5k7i3rolj7hed7li2ox"
                    :f/context
                    "fluree:memory://b6dcf8968183239ecc7a664025f247de5b7859ac18cdeaace89aafc421eeddee"]]
-                @(fluree/query db* {:select ['?s '?p '?o]
-                                    :where  [['?s '?p '?o]]}))))))))
+                 @(fluree/query db* {:select ['?s '?p '?o]
+                                     :where  [['?s '?p '?o]]})))))
+      (testing "Illegal reference queries"
+        (let [test-subject @(fluree/query db {:select ['?s '?p]
```
Comment (dpetran) [inline test/fluree/db/query/misc_queries_test.clj:243]: Is it possible to have a query of the form `{:select ['?s] :where [['?s '?p <some-actual-ref-iri>]]}`? Either way I think it would be nice to have a test for that to make the intended behavior clear.

File: src/fluree/db/query/exec/where.cljc [hunk 4]
```diff
@@ -12,13 +12,21 @@
 
 #?(:clj (set! *warn-on-reflection* true))
 
+(defn reference?
+  [mch]
```
Comment (dpetran) [inline src/fluree/db/query/exec/where.cljc:16]: I think `mch` is an abbreviation for "match", but it took me a few seconds to come up with that. I don't think we're saving too much space by abbreviating here and just using the full name would make it easier to read in the future.

File: test/fluree/db/query/misc_queries_test.clj (hunk 3 above)
Comment (zonotope) [reply test/fluree/db/query/misc_queries_test.clj:243]: No, that will (and should) throw an exception. If you want to specify that an object is an actual reference, you have to use the `@id` predicate:

```clojure
'{:select [?s]
  :where [[?s :id <some ref>]]}
```

I have added a test for that.
