### PR TITLE
Fix/flaky tests

### LINKED ISSUE #610: flaky tests
There are some shacl tests that are not deterministically passing. This means that our flake creation is sometimes creating flakes and sometimes not, and that's important to get right. This ticket is to track that investigation.

Discovered in the course of #611

### PR DESCRIPTION
**Pull request by dpetran**
Now that subject ids aren't always issued in the same order, some assumptions we used to make about flake ordering don't hold. This PR fixes some flaky tests that were a result of those violated assumptions.

Fixes #610

### CODE REVIEW

File: test/fluree/db/shacl/shacl_basic_test.clj [hunk 1]
```diff
@@ -1675,16 +1679,18 @@ WORLD! does not match pattern \"hello   (.*?)world\" with provided sh:flags: [\"
...
+              "type" "ex:Hand",
+              "ex:digit"
+              [{"ex:name" "Finger"}
+               {"ex:name" "Finger"}
+               {"ex:name" "Finger"}
+               {"ex:name" "Finger"}
+               {"ex:name" "Thumb"}]}
+             (-> @(fluree/query valid-hand {"select" {"?s" ["*" {"ex:digit" ["ex:name"]}]}
+                                            "where"  [["?s" "id" "ex:ValidHand"]]})
+                 (first)
```
Comment (cap10morgan) [inline test/fluree/db/shacl/shacl_basic_test.clj:1692]: Just `first` might be better for consistency's sake.

**Review by cap10morgan — APPROVED** [review]
Need to align some map key-value pairs and one teeny, tiny consistency thing. But once those very minor issues are dealt with looks good to me!
