### PR TITLE
return @type instead of rdf:type

### LINKED ISSUE #537: Data transacted with exclusively `rdf:type` predicates can't be queried by that nor `@type`
Steps to reproduce:

1. Transact some data with `"rdf:type"` predicates (with `"rdf"` aliased to `"http://www.w3.org/1999/02/22-rdf-syntax-ns#"` as we typically do in the context) and no other `type` / `@type` predicates in any of the data.
2. Try querying for data with `"rdf:type"` or `"@type"` predicates.

Expected result:

The data transacted is returned in the query results.

Observed:

No results or an `Undefined RDF type specified` exception.

### PR DESCRIPTION
**Pull request by dpetran**
Fixes https://github.com/fluree/db/issues/551

Uses the json-ld `@type` keyword instead of the rdf `http://www.w3.org/1999/02/22-rdf-syntax-ns#type` IRI.

Also fixes #537 by throwing an error during insert if it comes across the `rdf:type` IRI.

### CODE REVIEW

File: dev/indexing_test.clj [hunk 1]
```diff
@@ -68,7 +68,7 @@
 
   @(fluree/query (fluree/db ledger)
                  {:select {'?s [:* {:schema/isBasedOn [:*]}]}
-                  :where  [['?s :rdf/type :schema/Movie]]})
+                  :where  [['?s :type :schema/Movie]]})
```
Comment (bplatz) [inline dev/indexing_test.clj:71]: `rdf:type` or `@type` should work the same for a query - so these shouldn't need changing, but it shouldn't hurt to to change them either.

It is in the responses, when doing a graph crawl specifically, that we should default to returning `@type` instead of defaulting to `rdf:type`.

SPARQL will parse near directly into FlureeQL, and @type doesn't exist in SPARQL... so we don't want to loose rdf:type. SPARQL does not support a graph crawl response, which is where we are in unique Fluree land... and that is why it makes sense to change the default behavior there.

Comment (dpetran) [reply dev/indexing_test.clj:71]: Good point, I've added an explicit test that shows the following:
1) you cannot transact with an `rdf:type` predicate
2) you can query with an `rdf:type` predicate and it behaves the same as using `@type`

**Review by mpoffald — APPROVED** [review]
🍍
